setwd("S:/Shared/Documents/Study/VU/MSc Year 1/Experimental Design and Data Analysis/Assignments/Assignment 1")
dataset = read.table('./Datasets/clouds.txt', header = TRUE)
par(mfrow=c(2,2))
# 1x sqrt
seeded = sqrt(dataset$seeded)
unseeded = sqrt(dataset$unseeded)
hist(seeded, main=("Histogram of 1x sqrt seeded"))
hist(unseeded, main=("Histogram of 1x sqrt unseeded"))
qqnorm(seeded, main=("Q-Q Plot of 1x sqrt seeded"))
qqnorm(unseeded, main=("Q-Q Plot of 1x sqrt unseeded"))
t.test(seeded, unseeded,paired = FALSE, conf.level = 0.95, exact=FALSE)
wilcox.test(seeded, unseeded,paired = FALSE, conf.level = 0.95, exact=FALSE)
ks.test(seeded, unseeded,paired = FALSE, conf.level = 0.95, exact=FALSE)

# 2x sqrt
seeded2 = sqrt(seeded)
unseeded2 = sqrt(unseeded)
hist(seeded2,  main=("Histogram of 2x sqrt seeded"))
hist(unseeded2,main=("Histogram of 2x sqrt unseeded"))
qqnorm(seeded2,main=("Q-Q Plot of 2x sqrt seeded"))
qqnorm(unseeded2, main=("Q-Q Plot of 2x sqrt unseeded"))
t.test(seeded2, unseeded2,paired = FALSE, conf.level = 0.95, exact=FALSE)
wilcox.test(seeded2, unseeded2,paired = FALSE, conf.level = 0.95, exact=FALSE)
ks.test(seeded2, unseeded2,paired = FALSE, conf.level = 0.95, exact=FALSE)