setwd("S:/Shared/Documents/Study/VU/MSc Year 1/Experimental Design and Data Analysis/Assignments/Assignment 1")
dataset = read.table('./Datasets/dogs.txt', header = TRUE)
par(mfrow=c(2,3))

hist(dataset$isofluorane)
hist(dataset$halothane)
hist(dataset$cyclopropane)
qqnorm(dataset$isofluorane)
qqnorm(dataset$halothane)
qqnorm(dataset$cyclopropane)
